# Generated by Django 3.2.5 on 2021-10-23 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enterdata', '0002_auto_20211022_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='birder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
