# Generated by Django 3.2.5 on 2021-10-24 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enterdata', '0003_species_birder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='location',
            new_name='country',
        ),
        migrations.AddField(
            model_name='species',
            name='county',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='postcode',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
