# Generated by Django 3.2.5 on 2021-10-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterdata', '0004_auto_20211024_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('postcode', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='species',
            name='country',
        ),
        migrations.RemoveField(
            model_name='species',
            name='county',
        ),
        migrations.RemoveField(
            model_name='species',
            name='postcode',
        ),
    ]
