# Generated by Django 3.2.5 on 2021-10-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterdata', '0006_species_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geography',
            options={'ordering': ['county']},
        ),
        migrations.AlterField(
            model_name='species',
            name='date_seen',
            field=models.DateField(blank=True),
        ),
    ]
