# Generated by Django 3.2.5 on 2021-10-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterdata', '0008_alter_species_birder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='birder',
        ),
    ]
