# Generated by Django 3.2.5 on 2021-10-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterdata', '0010_auto_20211027_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='name',
            new_name='full_name',
        ),
    ]
