# Generated by Django 3.2.5 on 2021-10-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterdata', '0011_rename_name_species_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='full_name',
            new_name='species_name',
        ),
    ]
