# Generated by Django 3.2.5 on 2021-10-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterdata', '0012_rename_full_name_species_species_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='species_name',
            new_name='name',
        ),
    ]
