# Generated by Django 3.2.5 on 2021-10-25 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterdata', '0006_species_location'),
        ('displaydata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayform',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterdata.geography'),
        ),
    ]
