# Generated by Django 3.2.5 on 2021-10-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaydata', '0002_alter_displayform_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayform',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='displayform',
            name='to_date',
            field=models.DateField(),
        ),
    ]
