# Generated by Django 3.2.5 on 2021-10-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterdata', '0010_auto_20211027_1929'),
        ('displaydata', '0003_auto_20211026_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayform',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enterdata.geography'),
        ),
        migrations.AlterField(
            model_name='displayform',
            name='species_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enterdata.species'),
        ),
    ]
